name: Deploy Frontend JLPWA Staging

on:
  push:
    branches:
      - release
jobs:
  release-frontend:
    name: Release Frontend
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    strategy:
      matrix:
        node-version: [18.x]
    defaults:
      run:
        shell: bash
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: yarn install

      - name: Build Application
        run: yarn build:staging
        env:
          NODE_ENV: test

      - uses: jakejarvis/s3-sync-action@master
        name: Upload App to S3 Bucket
        with:
          args: --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.S3_DEPLOY_STAGING_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.S3_BUCKET_REGION }}
          SOURCE_DIR: 'dist'

      - name: Create CloudFront Cache Invalidation
        uses: chetan/invalidate-cloudfront-action@master
        env:
          DISTRIBUTION: ${{ secrets.STAGING_JLPWA_CLOUDFRONT_DISTRIBUTION_ID }}
          PATHS: '/*'
          AWS_REGION: ${{ secrets.S3_BUCKET_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Build and upload artifact for prod

      - name: Build Application
        run: yarn build

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: jlpwa
          path: dist

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: jlpwa

      - name: Zip Artifact
        run: |
          zip -r jlpwa.zip dist

      - name: Create Release Tag
        id: create-release-tag
        run: echo "tag_name=$(printf %04d $GITHUB_RUN_NUMBER)" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.create-release-tag.outputs.tag_name }}
          name: jlpwa-${{ steps.create-release-tag.outputs.tag_name }}
          body: |
            ## Info
            Commit ${{ github.sha }} was deployed to `staging`. [See code diff](${{ github.event.compare }}).

            It was initialized by [${{ github.event.sender.login }}](${{ github.event.sender.html_url }}).

          files: jlpwa.zip

      - name: Slack notification for build
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_CHANNEL: jet_deployments
          SLACK_MESSAGE: 'Just built and deployed latest staging version of jlpwa at https://jl.staging.jetstreamafrica.com'
          SLACK_TITLE: 'AWS S3 Deployment'
          SLACK_USERNAME: 'jetbot'
          SLACK_ICON_EMOJI: ':eyes:'
          SLACK_COLOR: ${{ job.status }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          MSG_MINIMAL: true
